#!/usr/bin/env python3
"""Generates the C# protocol enums from spec/protocol.json.

There are 445 message types across 25 protocols: writing them by hand is
impractical and drifts out of sync. This generator is the single source of
truth.

Usage (inside the container):
    python3 tools/generate_protocol_cs.py spec/protocol.json src/Bsgo.Protocol/Generated
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

HEADER = """// <auto-generated>
//     Generated by tools/generate_protocol_cs.py from spec/protocol.json.
//     DO NOT EDIT BY HAND: changes are lost on regeneration.
// </auto-generated>
#nullable enable

namespace Bsgo.Protocol;
"""


def csharp_name(name: str) -> str:
    """Avoids collisions with C# reserved words."""
    reserved = {"base", "class", "event", "object", "string", "new", "default", "lock", "params"}
    return f"@{name}" if name in reserved else name


def render_enum(name: str, base: str, members: dict[str, int], summary: str) -> str:
    if not members:
        return ""
    lines = [f"/// <summary>{summary}</summary>", f"public enum {name} : {base}", "{"]
    # Sorting by value keeps the file stable between regenerations.
    for member, value in sorted(members.items(), key=lambda kv: (kv[1], kv[0])):
        lines.append(f"    {csharp_name(member)} = {value},")
    lines.append("}")
    return "\n".join(lines)


def main() -> int:
    spec_path = Path(sys.argv[1] if len(sys.argv) > 1 else "spec/protocol.json")
    out_dir = Path(sys.argv[2] if len(sys.argv) > 2 else "src/Bsgo.Protocol/Generated")
    spec = json.loads(spec_path.read_text(encoding="utf-8"))

    out_dir.mkdir(parents=True, exist_ok=True)
    for stale in out_dir.glob("*.g.cs"):
        stale.unlink()

    # --- ProtocolId: the routing enum ------------------------------------
    (out_dir / "ProtocolId.g.cs").write_text(
        HEADER
        + "\n"
        + render_enum(
            "ProtocolId",
            "byte",
            spec["protocol_ids"],
            "Target protocol of a message. First byte of the body.",
        )
        + "\n",
        encoding="utf-8",
    )

    # --- Enums shared across protocols -----------------------------------
    shared = spec.get("shared_enums", {})
    if shared:
        blocks = [
            render_enum(
                name,
                enum["wire_type"],
                enum["members"],
                f"Shared with the client ({enum['source']}), "
                f"travels as {enum['wire_type']}.",
            )
            for name, enum in sorted(shared.items())
        ]
        (out_dir / "Shared.g.cs").write_text(
            HEADER + "\n" + "\n\n".join(blocks) + "\n", encoding="utf-8")

    # --- One file per protocol with its Request / Reply ------------------
    generated = 0
    for short, proto in sorted(spec["protocols"].items()):
        blocks = [
            render_enum(
                f"{short}Request",
                "ushort",
                proto["requests"],
                f"Client -> server messages of the {short} protocol (id {proto['id']}).",
            ),
            render_enum(
                f"{short}Reply",
                "ushort",
                proto["replies"],
                f"Server -> client messages of the {short} protocol (id {proto['id']}).",
            ),
        ]
        for enum_name, members in sorted(proto["other_enums"].items()):
            blocks.append(
                render_enum(
                    f"{short}{enum_name}",
                    "int",
                    members,
                    f"Auxiliary enum {enum_name} of the {short} protocol.",
                )
            )

        body = "\n\n".join(b for b in blocks if b)
        if not body:
            continue
        (out_dir / f"{short}.g.cs").write_text(HEADER + "\n" + body + "\n", encoding="utf-8")
        generated += 1

    print(f"generated {generated + 1} files in {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
